name: Main Hotfix Cleanup

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge-main-into-staging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/create-pull-request@v4
      - name: Set Git Config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge Main into Staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/main -m "Auto-merge Main into Staging after hotfix"
          git push

      - name: Create Pull Request on Failure
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.github_token }}
          author: ${{ github.actor }}
          title: 'Automated PR - Merge Conflict Between Main and Staging'

  merge-main-into-dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    steps:
      - uses: actions/checkout@v3
      - name: Set Git Config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge Main into Dev
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff origin/main -m "Auto-merge Main into Dev after hotfix"
          git push
