name: Main Hotfix Cleanup

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge-main-into-staging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    steps:
      - uses: actions/checkout@v2
      - name: Set Git Config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge Main into Staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/main -m "Auto-merge Main into Staging after hotfix"
          git push

        if: ${{ failure() }}
      - name: If Merge Failed
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automatic PR made from failure to merge Main into Staging'

  merge-main-into-dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    steps:
      - uses: actions/checkout@v2
      - name: Set Git Config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge Main into Staging
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff origin/main -m "Auto-merge Main into Dev after hotfix"
          git push

        if: ${{ failure() }}
      - name: If Merge Failed
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automatic PR made from failure to merge Main into Dev'
